version: '3.9'

services:
  psql:
    image: postgres:14.4-alpine3.16
    restart: always
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=api_db
    volumes:
      - db_pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  db_pg_data: