version: '3.9'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
      target: local
      args:
        UID: 1000
        GID: 1000
        USR: appuser
        GRP: appgrp
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./
        target: /home/appuser/app
    networks:
      - app-network
    env_file:
      - ./.env
    depends_on:
      - psql

  psql:
    image: postgres:14.4-alpine3.16
    restart: always
    container_name: db-local
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=api_db
    volumes:
      - db_pg_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - app-network

volumes:
  db_pg_data:

networks:
  app-network:
    name: app-network
